name: CI / CD Pipeline
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  build_and_test:
  name: Executando o Job de Test
  runs- on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Passo 01
      run: echo "Executando Passo 01"
      
    - name: Passo 02
      run: echo "Executando passo 02"
      
    - name: Passo 03
      run: echo "Executando passo 03"